[theme]
primaryColor="#5bbf83"
backgroundColor="#333333"
secondaryBackgroundColor="#111111"
textColor="#ffffff"


[server]

maxUploadSize = 2000


[browser]
gatherUsageStats = false


[client]
toolbarMode = "auto"
showSidebarNavigation = false

